### ISSUE TITLE
Maybe the same augumented graphs will be added

### ISSUE THREAD

**Issue by Jia-zb** [16372212/CLARA#1]
https://github.com/16372212/CLARA/blob/fd7123f5a7484d50c77763866aacbcf26cc8ef6b/prepare/matrix_to_huge_dgl.py#L348
Hello, I have a question about the code. Will some of the same argumented graphs be added here? (In some cases there may be identical edges added in for-loop so that there will be some duplicate argumented graphs.)

**Comment by 16372212** [comment]
是的，这样确实会有相同的数据增强图被加进来，不过这对后续训练的影响可能并不大。后面如果有好的办法可以再尝试

**Comment by Jia-zb** [comment]
Thanks for your reply~
